name: who_goes_first
description: Who goes first?

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^5.0.1
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/icon/Icon-512.png

  fonts:
    - family:  CustomIcons
      fonts:
       - asset: fonts/CustomIcons.ttf

